name = "portaguac"
version = "0.0.1"

description = "Markup for dynamic recipes"
licences = ["MIT"]
repository = { type = "github", user = "itsTurner", repo = "portaguac" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
simplifile = ">= 2.0.0 and < 3.0.0"
argv = ">= 1.0.2 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
